name: ktc_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_sticky_header: ^0.6.5
  flutter_pickers: ^2.1.9
  animated_splash_screen: ^1.3.0

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
   - assets/logo.jpg
   - assets/logo.png
   - assets/action.png
   - assets/sales.png
   - assets/trend.png
   - assets/one-day.png
   - assets/month.png
   - assets/calendar.png
   - assets/diversity.png
   - assets/whatsapp.png
   - assets/bin.png
   - assets/pen.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts\Montserrat-Regular.ttf
        - asset: fonts\Montserrat-ExtraBold.ttf
        - asset: fonts\Montserrat-SemiBold.ttf
        - asset: fonts\Montserrat-Light.ttf
        - asset: fonts\Montserrat-ExtraBoldItalic.ttf
        - asset: fonts\Montserrat-BoldItalic.ttf

